# Generated by Django 4.2 on 2023-04-16 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name="Category name"),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name="Country name"),
                ),
                ("code2", models.CharField(blank=True, max_length=2, null=True, verbose_name="Two letter code")),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("uuid", models.UUIDField(primary_key=True, serialize=False, verbose_name="UUID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("external_id", models.BigIntegerField(unique=True, verbose_name="External id")),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("launch_date", models.DateField(verbose_name="Date the project was launched")),
                ("deadline_date", models.DateField(verbose_name="Deadline for crowdfunding")),
                (
                    "goal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Amount of money the creater needs to complete the project (USD)",
                    ),
                ),
                (
                    "pledged",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Amount of money pledged to by the crowd (USD)",
                    ),
                ),
                ("backers", models.IntegerField(default=0, verbose_name="Number of backers")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="projects.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="projects.country",
                        verbose_name="Country of product origin",
                    ),
                ),
                (
                    "sub_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="projects.category",
                        verbose_name="Sub-category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
    ]
