# Generated by Django 4.2 on 2023-04-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_create_models_for_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="state",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (None, "(Unknown)"),
                    (0, "Live"),
                    (1, "Cancelled"),
                    (2, "Suspended"),
                    (3, "Failed"),
                    (4, "Successful"),
                ],
                null=True,
                verbose_name="Current condition the project",
            ),
        ),
    ]
