# Generated by Django 4.2 on 2023-04-17 16:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_add_state_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="UUID"
            ),
        ),
    ]
