[tool.black]
line-length = 120
target-version = ['py310']
include = '\.pyi?$'

[tool.isort]
profile = "django"
combine_as_imports = true
include_trailing_comma = true
line_length = 120

[tool.pylint."MESSAGES CONTROL"]
max-line-length = 120
disable = "missing-module-docstring, missing-function-docstring, missing-class-docstring, fixme, too-few-public-methods"
